github:
  - jakubambrus

patreon:
  - jakubambrus

open_collective:
  - jakubambrus

ko_fi:
  - jakubambrus

buymeacoffee:
  - jakubambrus

custom:
  - name: PayPal
    url: https://paypal.me/JakubAmbrus
